### ISSUE TITLE
anyOf support for required properties would be very helpful

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/jschema#102]

**Comment by lgolding** [comment]
Given this schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "a": {
      "type": "integer",
    },
    "b": {
      "type": "integer",
    }
  },
  "anyOf": [
    {
      "required": [ "a" ]
    },
    {
      "required": [ "b" ]
    }
  ]
}
```
this document is valid:
```
{
  "a": 1
}
```
and so is this one:
```
{
  "b": 1
}
```
but not this one:
```
{
}
```

Try it at https://www.jsonschemavalidator.net/.

**Comment by lgolding** [comment]
@michaelcfanning Json.Schema.Validation does support `anyOf`. The only thing wrong is a typo in the error message. Given the schema above, and the empty instance document shown, running the validator gives:
```
JSON Schema Validation Tool version 0.61.0.0
c Microsoft Corporation. All rights reserved.

C:\Users\Larry Golding\Desktop\jschema#102\a.json(1): error JSON1017: at "": The instance does validate successfully against any of the 2 schemas specified by "anyOf".
Validation time: 00:00:00.1538983
```
... when it should say "does not validate...". Did you see any other problem?

**Comment by lgolding** [comment]
@michaelcfanning Also, the code generator does the "right" thing -- by acccident, if you like -- when you bury a `"required"` property in an `"anyOf"`. Since there is no `"required"` property at the top level of the schema, the code generator refrains from marking any of the .NET properties as required, which is the right behavior.

**Comment by lgolding** [comment]
Re-closing. @michaelcfanning and I agree that JSchema validation correctly supports `anyOf`.
