### ISSUE TITLE
Provide options for marking types as sealed, members as virtual

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/jschema#111]
This could turn into a large item. In the short-term, would appreciate a switch where all types are emitted with virtual members.

In the future, some sensible defaults and the ability to control various things (e.g., marking specific properties as non-virtual, types as 'sealed') would make sense. SARIF doesn't need all this flexibility right away. But people are trying to create their own version of 'Result' and cannot do so.

**Comment by lgolding** [comment]
@michaelcfanning The code generator today has
```
[Option(
    "seal-classes",
    HelpText = "Seal generated classes.",
    Default = false,
    Required = false)]
```

... to seal _all_ classes (but there's no way to seal _specific_ classes).

Similarly I will add
```
[Option(
    'v',
    "virtual-members",
    HelpText = "Mark generated properties and methods as virtual.",
    Default = false,
    Required = false)]
```

... to mark _all_ members as `virtual` (but again, with no way to mark specific members as virtual).

This will be `false` by default, to avoid this being a breaking change. The SARIF SDK will invoke the code generator explicitly with `--virtual-members`.
