### ISSUE TITLE
JSchema doesn't initialize default values in ctor.

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/jschema#57]
JSchema doesn't emit default values. in the SARIF SDK we have to maintain these manually, currently

```C#
        /// </summary>
        [DataMember(Name = "columnKind", IsRequired = false, EmitDefaultValue = false)]
        [JsonConverter(typeof(EnumConverter))]
        [System.ComponentModel.DefaultValue(ColumnKind.UnicodeCodePoints)]
        public ColumnKind ColumnKind { get; set; }
```

**Comment by lgolding** [comment]
Also, make sure that default values are set on deserialization by setting
```
[JsonProperty DefaultValueHandling = DefaultValueHandling.Include)]
```
on every property.

@michaelcfanning FYI

**Comment by michaelcfanning** [comment]
Ah! JsonProperty can accommodate this. I think you need the Populate member for the deserialization scenario?

**Comment by michaelcfanning** [comment]
As you have pointed out separately, code gen hints can be used to apply these. More importantly, however, JSchema could populate default values in OM constructor. The attribute hints only work when serializing to and from JSON. Direct creation via the OM is not initializing the default values, requiring users to explicitly know about and set them. This issue is obviously more urgent than the application of attributes (agian, because there is an existing workaround).

        public Location()
        {
            LogicalLocationIndex = -1;
