### ISSUE TITLE
PackageLicenseExpression not working for Android bidning projects

### ISSUE THREAD

**Issue by LRP-sgravel** [Microsoft/jschema#87]
Tried to use the new attributes on an Android binding project but it does not output the <license> node in the nuspec.  It does work however for a multi-target NetStandard2.0 project.

**Comment by lgolding** [comment]
@LRP-sgravel I'm sorry, I don't know what an Android binding project is, or what new attributes you're referring to. Is it possible this issue belongs in another repo?

**Comment by LRP-sgravel** [comment]
Totally, this should have gone in the Nuget repo, sorry!
